name = input("დაწერე შენი სახელი: ")
print(name)
surname = input("დაწერე შენი გვარი: ") 
print(surname)
age = input("დაწერე შენი ასაკი:")
print(age)
date_of_birth = input("დაწერე შენი დაბადების წელი:")
print(date_of_birth)
Birth_number_and_month = input("დაწერე შენი დაბადების რიცხვი და თვე:")
print(Birth_number_and_month)